/*
------------------------------------------------------------------------------ 
This code was generated by Amplication. 
 
Changes to this file will be lost if the code is regenerated. 

There are other ways to to customize your code, see this doc to learn more
https://docs.amplication.com/how-to/custom-code

------------------------------------------------------------------------------
  */
import * as graphql from "@nestjs/graphql";
import { GraphQLError } from "graphql";
import { isRecordNotFoundError } from "../../prisma.util";
import { MetaQueryPayload } from "../../util/MetaQueryPayload";
import * as nestAccessControl from "nest-access-control";
import * as gqlACGuard from "../../auth/gqlAC.guard";
import { GqlDefaultAuthGuard } from "../../auth/gqlDefaultAuth.guard";
import * as common from "@nestjs/common";
import { AclFilterResponseInterceptor } from "../../interceptors/aclFilterResponse.interceptor";
import { DetectedObject } from "./DetectedObject";
import { DetectedObjectCountArgs } from "./DetectedObjectCountArgs";
import { DetectedObjectFindManyArgs } from "./DetectedObjectFindManyArgs";
import { DetectedObjectFindUniqueArgs } from "./DetectedObjectFindUniqueArgs";
import { DeleteDetectedObjectArgs } from "./DeleteDetectedObjectArgs";
import { DetectedObjectService } from "../detectedObject.service";
@common.UseGuards(GqlDefaultAuthGuard, gqlACGuard.GqlACGuard)
@graphql.Resolver(() => DetectedObject)
export class DetectedObjectResolverBase {
  constructor(
    protected readonly service: DetectedObjectService,
    protected readonly rolesBuilder: nestAccessControl.RolesBuilder
  ) {}

  @graphql.Query(() => MetaQueryPayload)
  @nestAccessControl.UseRoles({
    resource: "DetectedObject",
    action: "read",
    possession: "any",
  })
  async _detectedObjectsMeta(
    @graphql.Args() args: DetectedObjectCountArgs
  ): Promise<MetaQueryPayload> {
    const result = await this.service.count(args);
    return {
      count: result,
    };
  }

  @common.UseInterceptors(AclFilterResponseInterceptor)
  @graphql.Query(() => [DetectedObject])
  @nestAccessControl.UseRoles({
    resource: "DetectedObject",
    action: "read",
    possession: "any",
  })
  async detectedObjects(
    @graphql.Args() args: DetectedObjectFindManyArgs
  ): Promise<DetectedObject[]> {
    return this.service.detectedObjects(args);
  }

  @common.UseInterceptors(AclFilterResponseInterceptor)
  @graphql.Query(() => DetectedObject, { nullable: true })
  @nestAccessControl.UseRoles({
    resource: "DetectedObject",
    action: "read",
    possession: "own",
  })
  async detectedObject(
    @graphql.Args() args: DetectedObjectFindUniqueArgs
  ): Promise<DetectedObject | null> {
    const result = await this.service.detectedObject(args);
    if (result === null) {
      return null;
    }
    return result;
  }

  @graphql.Mutation(() => DetectedObject)
  @nestAccessControl.UseRoles({
    resource: "DetectedObject",
    action: "delete",
    possession: "any",
  })
  async deleteDetectedObject(
    @graphql.Args() args: DeleteDetectedObjectArgs
  ): Promise<DetectedObject | null> {
    try {
      return await this.service.deleteDetectedObject(args);
    } catch (error) {
      if (isRecordNotFoundError(error)) {
        throw new GraphQLError(
          `No resource was found for ${JSON.stringify(args.where)}`
        );
      }
      throw error;
    }
  }
}
