/*
------------------------------------------------------------------------------ 
This code was generated by Amplication. 
 
Changes to this file will be lost if the code is regenerated. 

There are other ways to to customize your code, see this doc to learn more
https://docs.amplication.com/how-to/custom-code

------------------------------------------------------------------------------
  */
import * as graphql from "@nestjs/graphql";
import { GraphQLError } from "graphql";
import { isRecordNotFoundError } from "../../prisma.util";
import { MetaQueryPayload } from "../../util/MetaQueryPayload";
import * as nestAccessControl from "nest-access-control";
import * as gqlACGuard from "../../auth/gqlAC.guard";
import { GqlDefaultAuthGuard } from "../../auth/gqlDefaultAuth.guard";
import * as common from "@nestjs/common";
import { AclFilterResponseInterceptor } from "../../interceptors/aclFilterResponse.interceptor";
import { MovementStatus } from "./MovementStatus";
import { MovementStatusCountArgs } from "./MovementStatusCountArgs";
import { MovementStatusFindManyArgs } from "./MovementStatusFindManyArgs";
import { MovementStatusFindUniqueArgs } from "./MovementStatusFindUniqueArgs";
import { DeleteMovementStatusArgs } from "./DeleteMovementStatusArgs";
import { MovementStatusService } from "../movementStatus.service";
@common.UseGuards(GqlDefaultAuthGuard, gqlACGuard.GqlACGuard)
@graphql.Resolver(() => MovementStatus)
export class MovementStatusResolverBase {
  constructor(
    protected readonly service: MovementStatusService,
    protected readonly rolesBuilder: nestAccessControl.RolesBuilder
  ) {}

  @graphql.Query(() => MetaQueryPayload)
  @nestAccessControl.UseRoles({
    resource: "MovementStatus",
    action: "read",
    possession: "any",
  })
  async _movementStatusesMeta(
    @graphql.Args() args: MovementStatusCountArgs
  ): Promise<MetaQueryPayload> {
    const result = await this.service.count(args);
    return {
      count: result,
    };
  }

  @common.UseInterceptors(AclFilterResponseInterceptor)
  @graphql.Query(() => [MovementStatus])
  @nestAccessControl.UseRoles({
    resource: "MovementStatus",
    action: "read",
    possession: "any",
  })
  async movementStatuses(
    @graphql.Args() args: MovementStatusFindManyArgs
  ): Promise<MovementStatus[]> {
    return this.service.movementStatuses(args);
  }

  @common.UseInterceptors(AclFilterResponseInterceptor)
  @graphql.Query(() => MovementStatus, { nullable: true })
  @nestAccessControl.UseRoles({
    resource: "MovementStatus",
    action: "read",
    possession: "own",
  })
  async movementStatus(
    @graphql.Args() args: MovementStatusFindUniqueArgs
  ): Promise<MovementStatus | null> {
    const result = await this.service.movementStatus(args);
    if (result === null) {
      return null;
    }
    return result;
  }

  @graphql.Mutation(() => MovementStatus)
  @nestAccessControl.UseRoles({
    resource: "MovementStatus",
    action: "delete",
    possession: "any",
  })
  async deleteMovementStatus(
    @graphql.Args() args: DeleteMovementStatusArgs
  ): Promise<MovementStatus | null> {
    try {
      return await this.service.deleteMovementStatus(args);
    } catch (error) {
      if (isRecordNotFoundError(error)) {
        throw new GraphQLError(
          `No resource was found for ${JSON.stringify(args.where)}`
        );
      }
      throw error;
    }
  }
}
